/*##############################################################################
SugzTools Parser Test Script Library
Version 1.02
Script By Clément "Sugz" Plantec
plantec.clement@gmail.com

# Description:
This is a simple test file to parse it !

# Required Components:
Component 1
Component 2

# Sources:
Machin from: https://github.com/Sugz/SugzTools
L'autre mec là: http://www.phoenixjp.net/news/fr/index.php?page=2

# ToDo:

# History:
1.02:
	- On rigole zero 
	- Truc de fou trop awesome
1.01:
	- Added TestFunction()

*Use / Modify this script at your own risk !*
###############################################################################*/


fn TestFunction arg opt:arg2 =
(
	/*<Function>
	Description:
		Not much here...
	Arguments:
		Integer arg: un argument quoi
		String arg2: un argument optionel <Optional> 
	Return:
	Infos:
		Var taMere: dans http://forum.mattguetta.com ton cul ! 
	</Function>*/
	
	

)




