global myVar =1.56test -- test com

function Osef = 
(
	test = "this is a string -- fkl /*fhejz*/ " -- com in line
)


/* First struct ############################################################################################*/
struct TestStruct 
(

	/* First test function with inside description ############################################################################################*/
	fn TestFunction arg opt:arg2 =
	(
		/*<Function>
		Arguments:
			<Integer> arg: un argument quoi "with a string"
			<String> arg2: un argument optionel <Optional> 
		Return:
		Infos:
			<Var> taMere: dans http://forum.mattguetta.com ton cul ! 
		</Function>*/


		
	),


	/* Function with an additional description ############################################################################################*/
	fn Bouyaaa =
	(
		/*<Function>
			Additional hyperlink: https://stackoverflow.com/questions/15564944/remove-the-last-three-characters-from-a-string
		</Function>*/


		
	)


	
	
)



struct structWithCommentinbetween
/*<Struct>
Infos:
	<Var> taMere: dans http://forum.mattguetta.com ton cul ! 
</Struct>*/
(

	/* First test function with inside description ############################################################################################*/
	fn TestFunction arg opt:arg2 =
	(
		/*<Function>
		Arguments:
			<Integer> arg: un argument quoi
			<String> arg2: un argument optionel <Optional> 
		Return:
		Infos:
			<Var> taMere: dans http://forum.mattguetta.com ton cul ! 
		</Function>*/


		
	)
)



struct test( --lalala
/*<Struct>
Infos:
	<Var> taMere: dans http://forum.mattguetta.com ton cul ! 
</Struct>*/

	/* Function with just a top description ############################################################################################*/
	fn SimpleFunction =
	(
		
		
	)

)




/*##############################################################################
SugzTools Parser Test Script Library
Version 1.02
Script By Clément "Sugz" Plantec
plantec.clement@gmail.com

# Description:
This is a simple test file to parse it !

# Required Components:
Component 1
Component 2

# Sources:
Machin from: https://github.com/Sugz/SugzTools
L'autre mec là: http://www.phoenixjp.net/news/fr/index.php?page=2

# ToDo:

# History:
1.02:
	- On rigole zero 
	- Truc de fou trop awesome
1.01:
	- Added TestFunction()

*Use / Modify this script at your own risk !*
###############################################################################*/

